config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root "projects#index"

  resources :projects
  resources :tasks#, :collection => { :complete => :put }
  patch '/tasks/:id', to: 'tasks#complete', as: 'complete_task'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord

  # belongs_to :user
  has_many :tasks, inverse_of: :project, :dependent => :destroy

  accepts_nested_attributes_for :tasks, reject_if: :new_record?, allow_destroy: true

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project, inverse_of: :tasks

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_project, only: [:edit, :update, :destroy]
  before_action :all_projects, only: [:index, :create, :update, :destroy]
  respond_to :html, :js

  # GET /projects
  # GET /projects.json

  # GET /projects/1
  # GET /projects/1.json
  def index
    @projects = Project.all
    @tasks = Task.all
  end
  # GET /projects/new
  def new
    @project = Project.new
    @project.tasks.build
  end

  # GET /projects/1/edit


  # POST /projects
  # POST /projects.json
  def create
    @project = Project.create(project_params)
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @project.update_attributes(project_params)

  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy

  end


  private

    # def current_user
    #   @user = current_user
    # end

    def all_projects
      @projects = Project.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # before_action :set_project, except: [:edit]
  before_action :set_task, except: [:create, :new, :show]

  def new
    @task = Task.new
  end

  def create

    @task = Task.create(task_params)
    respond_to do |f|
      f.html { redirect_to projects_url }
      f.js
    end
  end

  def show

  end

  def edit
    # @task = Project.tasks.find(params[:id])
  end

  def update
    @task.update(task_params)
    @task.update_attributes(task_params)

    respond_to do |f|
      f.html { redirect_to projects_url }
      f.js
    end
  end

  def destroy
    if @task.destroy
      flash[:success] = "Task was deleted."
      respond_to do |f|
        f.html { redirect_to projects_url }
        f.js
      end
    else
      flash[:error] = "Task could not be deleted."
    end
  end



  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params[:task].permit(:title, :done, :deadline, :project_id)
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def link_to_add_fields(name, p, association)
      new_object = p.object_id.send(association).klass.new
      id = new_object.object_id
      fields = f.fields_for(association, new_object, child_index: id) do |builder|
        render(association.to_s.singularize + "_fields", p: builder)
      end
      link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<div class="text-center">
  <h2 calss="page-header">SIMPLE TODO LISTS</h2>
  <h6 class="page-header"> FROM RUBY GARAGE</h6>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleList</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <div id="container">
      <div id="used_nav">
        <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path %> |
            <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>
    </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <div class="container-fluid">
      <div class="row" id="header"><%= render 'layouts/header' %></div>
      <div class="row content"><%= yield %></div>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, remote: true do |f| %>
    <div class="field">
         <%= f.text_field :title, placeholder: "New Project" %>
         <%= f.submit "Add" %>
    </div>
<% end %>

app/views/projects/_project.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-2" id="edit-form" style="display:none;"></div>
</div>

<% @projects.each do |p| %>
  <table class="table table-hover">
    <thead class="table_project_title">
      <tr data-item-id=<%= p.id %> class="item">
        <td>
          <h4>
          <%= p.title %>
          </h4>
        </td>
          <td class="button">
          <%= link_to edit_project_path(p), remote: true do %>
              <span class="glyphicon glyphicon-pencil"> </span>
          <% end %>
          </td>
        <td class="button">
          <%= link_to p, remote: true, method: :delete,
                        data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"> </span>
          <% end %>
        </td>
      </tr>
      <tr id="task-form">
        <td class="render-task" colspan="3">
          <% @task = Task.new%>
          <% @project_id = p.id %>
          <%= render "tasks/form" %>
        </td>
      </tr>
    </thead>
    <tbody class="table_task_title">
    <div class="row">
      <div class="col-md-7 col-md-offset-1" id="tasks">
    <% p.tasks.each do |task| %>
    <% @task = task %>
            <% @project_id = params[:project_id] %>
            <tr>
              <td id = "update-task">
                <%= render "tasks/task" %>
              </td>
            <td class="button">
              <%= link_to edit_task_path(task), remote: true do %>
                  <span class="glyphicon glyphicon-pencil"> </span>
              <% end %>
            </td>

            <td class="button-edit">
              <%= link_to task, remote:true, method: :delete do %>
                  <span class="glyphicon glyphicon-trash"> </span>
              <% end %>

              </td>
            </tr>
            <div class="row">
              <div class="col-md-6 col-md-offset-2" id="task-form" style="display:none;"></div>
            </div>
      <% end %>
      </div>
    </div>
    </tbody>
  </table>
  <% end %>

app/views/projects/create.js.erb
$('#projects').html("<%= escape_javascript(render @project) %>");
$('#project-form').slideUp(350);

app/views/projects/destroy.js.erb
$('#projects').html("<%= escape_javascript(render partial:@project) %>");

app/views/projects/edit.js.erb
$('#project-form').html("<%= escape_javascript(render 'form' ) %>");
$('#project-form').slideDown(350);

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-2" id="project-form" style="display:none;"></div>
</div>

<div class="row">
  <div class="col-md-7 col-md-offset-1" id="projects">

    <%= render "projects/project" %></div>
</div>

<div class="col-md-2 col-md-offset-4">
  <%= link_to new_project_path, remote: true do %>
      <button class="btn btn-primary">Add TODO List</button>
  <% end %>
</div>

app/views/projects/new.js.erb
$('#project-form').html("<%= j (render 'form') %>");
$('#project-form').slideDown(350);

app/views/projects/show.js.erb
$('#projects').html("<%= j render(partial: 'index') %>");
$('#projects').setInterval('show()',1000);

app/views/projects/update.js.erb
$('#projects').html("<%= escape_javascript(render :partial => @project )%>");


$('#project-form').slideUp(350);

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f| %>
    <%= f.text_field :title, placeholder: "Start typing here to create a task..." %>
    <%= f.date_select :deadline %>
    <%= f.hidden_field :project_id, :value => @project_id %>
    <%= f.submit "Add Task" %>
<% end %>

app/views/tasks/_task.html.erb
<% task = @task %>

<%= form_for task, remote: true do |f| %>

  <div data-item-id=<%= task.id %> class="item">

      <div id="complete">
        <label class="checkbox">
          <input type="checkbox" value="">
          <%= task.title %>
        </label>
      </div>
  </div>
<% end %>

app/views/tasks/create.js.erb
$('#project > #task-form').show();
$('#project > #tasks').html("<%= j (render @task) %>");

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

app/views/tasks/edit.js.erb
$('#edit-form').html("<%= escape_javascript(render 'form' ) %>");
$('#edit-form').slideDown(350);

app/views/tasks/new.js.erb
$('#project > #task-form').html("<%= j (render 'form') %>");

app/views/tasks/update.js.erb
<% if @task.done? %>
  $('#edit_task_<%= @task.id %>').appendTo('#complete');
  $('#update-task').html("<%= escape_javascript(render :partial => @task )%>");
  $('#edit-form').slideUp(350);
<% else %>
  $('#edit_task_<%= @task.id %>').appendTo('#incomplete');
  $('#update-task').html("<%= escape_javascript(render :partial => @task )%>");
  $('#edit-form').slideUp(350);
<% end %>